(function(){
  'use strict';
  function txt(el){return (el && (el.innerText||el.textContent)||'').trim().toLowerCase()}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function style(){if(document.getElementById('compat-style'))return;var s=document.createElement('style');s.id='compat-style';s.textContent='.compatOv{position:fixed;inset:0;background:rgba(20,22,28,.55);z-index:99999;display:flex;align-items:flex-end;justify-content:center;padding:14px}.compatBox{width:min(620px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:22px;padding:20px;box-sizing:border-box;box-shadow:0 18px 60px rgba(0,0,0,.25);font-family:Arial,sans-serif;color:#252830}.compatBox h3{margin:0 0 14px;font-size:24px}.compatGrid{display:grid;gap:10px}.compatGrid input,.compatGrid textarea{width:100%;box-sizing:border-box;padding:12px 14px;border:1px solid #d8dce3;border-radius:12px;font:inherit}.compatRow{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.compatBtn{border:0;border-radius:14px;padding:13px 18px;font-weight:700;font-size:16px;cursor:pointer}.compatRed{background:#d71920;color:#fff}.compatLight{background:#f2f3f5;color:#252830}.compatMsg{margin-top:10px;font-size:14px}.compatCall a{display:block;text-decoration:none;background:#d71920;color:#fff;padding:14px;border-radius:14px;margin-top:10px;text-align:center;font-weight:700}';document.head.appendChild(s)}
  function close(){var x=document.getElementById('compat-ov');if(x)x.remove()}
  function overlay(html){style();close();var ov=document.createElement('div');ov.className='compatOv';ov.id='compat-ov';ov.innerHTML='<div class="compatBox">'+html+'</div>';ov.addEventListener('click',function(e){if(e.target===ov)close()});document.body.appendChild(ov);return ov}
  function calls(){overlay('<h3>Подзвонити Андрію</h3><div class="compatCall"><a href="tel:+380665628743">Vodafone · +38 (066) 562-87-43</a><a href="tel:+380969897456">Kyivstar · +38 (096) 989-74-56</a></div><div class="compatRow"><button class="compatBtn compatLight" id="compat-close">Закрити</button></div>');document.getElementById('compat-close').onclick=close}
  function request(){var ov=overlay('<h3>Залишити заявку</h3><div class="compatGrid"><input id="cf-name" placeholder="Ім’я"><input id="cf-phone" placeholder="Телефон, напр. 0951234567"><input id="cf-machine" placeholder="Техніка"><input id="cf-brand" placeholder="Марка"><input id="cf-model" placeholder="Модель"><textarea id="cf-issue" rows="3" placeholder="Опишіть проблему"></textarea><input id="cf-error" placeholder="Код помилки, якщо є"><input id="cf-photo" type="file" accept="image/*"></div><div class="compatRow"><button class="compatBtn compatRed" id="cf-send">Надіслати заявку</button><button class="compatBtn compatLight" id="cf-close">Скасувати</button></div><div class="compatMsg" id="cf-msg"></div>');document.getElementById('cf-close').onclick=close;document.getElementById('cf-send').onclick=function(){submitFallback()}}
  function xhr(payload,cb){var x=new XMLHttpRequest();x.open('POST','/api/request',true);x.setRequestHeader('Content-Type','application/json');x.onreadystatechange=function(){if(x.readyState!==4)return;var j={};try{j=JSON.parse(x.responseText||'{}')}catch(e){};cb(x.status>=200&&x.status<300&&j.ok,j.error||j.description||('HTTP '+x.status))};x.onerror=function(){cb(false,'network')};x.send(JSON.stringify(payload))}
  function photoData(file,done){if(!file){done('','');return}var r=new FileReader();r.onload=function(){done(String(r.result||''),file.name||'photo.jpg')};r.onerror=function(){done('','')};r.readAsDataURL(file)}
  function submitFallback(){var g=function(id){var e=document.getElementById(id);return e?e.value.trim():''};var phone=g('cf-phone').replace(/[\s()\-]/g,'');var msg=document.getElementById('cf-msg');if(!g('cf-name')||!phone||!g('cf-machine')||!g('cf-brand')||!g('cf-model')||!g('cf-issue')){msg.textContent='Заповніть, будь ласка, основні поля.';return}var file=document.getElementById('cf-photo').files[0];msg.textContent='Надсилаю заявку…';photoData(file,function(pd,pn){var data={name:g('cf-name'),phone:phone,machine:g('cf-machine'),brand:g('cf-brand'),model:g('cf-model'),issue:g('cf-issue'),error:g('cf-error')||'Немає',changes:'',photoData:pd,photoName:pn};xhr({event:'service_request',data:data,occurredAt:new Date().toISOString()},function(ok,err){if(ok){document.querySelector('.compatBox').innerHTML='<h3>Заявку створено та передано Андрію ✅</h3><p>Він зв’яжеться з Вами за номером <b>'+esc(phone)+'</b>.</p><div class="compatRow"><button class="compatBtn compatRed" id="compat-close2">Готово</button></div>';document.getElementById('compat-close2').onclick=close}else{msg.textContent='Не вдалося передати заявку. '+err}})})}
  function mainBroken(){return typeof window.openConsult!=='function' || typeof window.openCallSheet!=='function'}
  document.addEventListener('click',function(e){if(!mainBroken())return;var el=e.target;while(el&&el!==document.body){var t=txt(el);if(t==='подзвонити'||t.indexOf('подзвонити')===0){e.preventDefault();e.stopPropagation();calls();return}if(t==='залишити заявку'||t.indexOf('залишити заявку')===0){e.preventDefault();e.stopPropagation();request();return}el=el.parentElement}},true);
  window.__compatRequest=request;window.__compatCalls=calls;
})();
